// Development-only certificates - DO NOT USE IN PRODUCTION
// These are dummy certificates for development purposes only
export const DEV_CERTIFICATES = {
  cert: process.env.DEV_SAML_CERTIFICATE || `-----BEGIN CERTIFICATE-----
MIIDazCCAlOgAwIBAgIUXHxwKHGYOXWJIgpJXUHgILGHNhwwDQYJKoZIhvcNAQEL
BQAwRTELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoM
GEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDAeFw0yMzEyMjAxMjAwMDBaFw0yNDEy
MTkyMzU5NTlaMEUxCzAJBgNVBAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEw
HwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQwggEiMA0GCSqGSIb3DQEB
AQUAA4IBDwAwggEKAoIBAQDHvF7+kJWVZFtx4sBr0TvmKGz0aCqw0DK2Wd+mOYvx
sB+AFWUvX7MF7h4HrQHX6Rh7O5wEVjqS9p2GaQWEb5xZh5GqB9UDtqM0yQeC2pRg
2MxbZeELf9uJwpYVwnZYYQ==
-----END CERTIFICATE-----`,
  privateKey: process.env.DEV_SAML_PRIVATE_KEY || `-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDHvF7+kJWVZFtx
4sBr0TvmKGz0aCqw0DK2Wd+mOYvxsB+AFWUvX7MF7h4HrQHX6Rh7O5wEVjqS9p2G
aQWEb5xZh5GqB9UDtqM0yQeC2pRg2MxbZeELf9uJwpYVwnZYYQ==
-----END PRIVATE KEY-----`
}; 